version : '3'
services:
  app:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: mongo:latest
    hostname: test_mongodb
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
    - 27017:27017
    
volumes:
  db-data:
    external: true
